// Exercise the shipped SQLite migration and triggers, independent of the UI fixture.
import { DatabaseSync } from "node:sqlite";
import { readFileSync } from "node:fs";
import assert from "node:assert/strict";
const db = new DatabaseSync(":memory:");
db.exec("PRAGMA foreign_keys=ON; CREATE TABLE projects(id TEXT PRIMARY KEY); CREATE TABLE workbench_migrations(version INTEGER PRIMARY KEY); CREATE TABLE work_entries(id TEXT PRIMARY KEY,content TEXT,kind TEXT,status TEXT,occurred_on TEXT,project_id TEXT,source_label TEXT);");
db.exec("INSERT INTO projects VALUES('p'),('other'); INSERT INTO work_entries VALUES('old','旧记录','progress','waiting','2026-09-01','p','随手记');");
const migration=readFileSync(new URL("../apps/desktop/src-tauri/src/project_hub_schema.sql",import.meta.url),"utf8");
db.exec("CREATE TABLE tasks(id TEXT PRIMARY KEY,title TEXT,completed INTEGER,source_type TEXT,source_id TEXT,owner TEXT,due_date TEXT); CREATE TABLE project_links(entity_type TEXT,entity_id TEXT,project_id TEXT);");
db.exec(migration);db.exec(migration);
assert.equal(db.prepare("SELECT count(*) n FROM entry_history").get().n,1);
db.exec("INSERT INTO activities VALUES('a','评审','review','2026-09-29',NULL,'now'); INSERT INTO activity_projects VALUES('a','p'),('a','other'); INSERT INTO resources VALUES('r','D:/report.docx','d:/report.docx','报告',12,'version-1','now'); INSERT INTO resource_activities VALUES('r','a','output');");
const context=JSON.stringify({activity:{id:"a",title:"评审"},resource:{id:"r",title:"报告",modifiedAt:"version-1"}});
db.prepare("INSERT INTO entry_context VALUES('e',?)").run(context);
db.exec("INSERT INTO work_entries VALUES('e','初稿已提交','progress','waiting','2026-09-29','p','项目进展'); UPDATE work_entries SET content='补充说明：等待反馈' WHERE id='e';");
const history=db.prepare("SELECT snapshot_json FROM entry_history WHERE entry_id='e' ORDER BY sequence").all().map(r=>JSON.parse(r.snapshot_json));
assert.equal(history.length,2);assert.equal(history[0].content,"初稿已提交");assert.equal(history[1].context.resource.modifiedAt,"version-1");
db.exec("UPDATE resources SET modified_at='version-2' WHERE id='r'; DELETE FROM resource_activities WHERE resource_id='r';");
assert.equal(JSON.parse(db.prepare("SELECT snapshot_json FROM entry_history WHERE entry_id='e' ORDER BY sequence LIMIT 1").get().snapshot_json).context.resource.modifiedAt,"version-1");
assert.equal(db.prepare("SELECT count(*) n FROM resources").get().n,1);
assert.throws(()=>db.exec("INSERT INTO activity_projects VALUES('missing','p')"));
db.exec("SAVEPOINT test_write; UPDATE work_entries SET content='不可保存的更正' WHERE id='e'; ROLLBACK TO test_write; RELEASE test_write;");
assert.equal(db.prepare("SELECT count(*) n FROM entry_history WHERE entry_id='e'").get().n,2);
assert.equal(db.prepare("PRAGMA foreign_key_check").all().length,0);
db.exec("INSERT INTO tasks VALUES('t','提交报告',0,'meeting','m','小林',NULL); INSERT INTO project_links VALUES('meeting','m','p'); UPDATE tasks SET completed=1 WHERE id='t'; UPDATE tasks SET title='更新报告标题' WHERE id='t'; UPDATE tasks SET completed=0 WHERE id='t';");
const taskEvents=db.prepare("SELECT * FROM task_history ORDER BY sequence").all();
assert.equal(taskEvents.length,2);
assert.equal(taskEvents[0].project_id,"p");
assert.equal(JSON.parse(taskEvents[0].snapshot_json).title,"提交报告");
assert.equal(JSON.parse(taskEvents[0].snapshot_json).completed,1);
assert.equal(JSON.parse(taskEvents[1].snapshot_json).completed,0);
db.close();
console.log("PASS: real SQLite migration idempotency, shared relationships, history snapshots, rollback and foreign-key integrity.");
