import { chromium } from "playwright";
import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { installFixture } from "./workbench-fixture.mjs";

function seed() {
  const f = window.__fixture;
  f.work.projects.push({ id: "p1", name: "季度汇报", archived: false }, { id: "p2", name: "专题调研", archived: false }, { id: "p3", name: "历史项目", archived: true });
  f.hub.resources.push({ id: "r1", title: "调研报告.docx", path: "D:\\work\\调研报告.docx", contentStatus: "metadata_only" }, { id: "r2", title: "评审意见.pdf", path: "D:\\work\\评审意见.pdf", contentStatus: "metadata_only" });
  f.hub.resourceLinks.push({ resourceId: "r1", projectId: "p1", role: "output" }, { resourceId: "r2", projectId: "p1", role: "reference" });
  localStorage.setItem("zhiji:last-project", "p1");
  if (!localStorage.getItem("zhiji:project-shortcuts")) localStorage.setItem("zhiji:project-shortcuts", "invalid old cache");
}

const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, locale: "zh-CN", timezoneId: "Asia/Shanghai" });
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.clock.install({ time: new Date("2026-10-02T10:00:00+08:00") });
await page.addInitScript({ content: `(${installFixture.toString()})(); (${seed.toString()})();` });
try {
  await page.goto(process.env.TEST_URL || "http://127.0.0.1:1422");
  await page.getByRole("region", { name: "继续上次项目" }).getByRole("button", { name: "继续项目" }).click();
  const hub = page.getByRole("region", { name: "项目详情" });
  await hub.getByRole("tab", { name: "概览", exact: true }).waitFor();
  await page.getByRole("button", { name: "收藏当前项目", exact: true }).click();
  const switchProject = page.getByRole("button", { name: /^切换项目/ });
  await switchProject.click();
  const search = page.getByRole("textbox", { name: "查找项目" });
  assert.equal(await search.evaluate(el => el === document.activeElement), true);
  await page.getByRole("navigation", { name: "收藏项目", exact: true }).getByRole("button", { name: "季度汇报", exact: true }).waitFor();
  assert.equal(await page.getByRole("navigation", { name: "项目列表", exact: true }).getByRole("button", { name: /历史项目/ }).count(), 0);
  await search.fill("专题");
  assert.equal(await page.getByRole("navigation", { name: "收藏项目", exact: true }).count(), 0, "search applies to shortcuts too");
  await search.press("Escape");
  assert.equal(await switchProject.evaluate(el => el === document.activeElement), true);
  await switchProject.click();
  await search.fill("");
  await page.getByRole("navigation", { name: "项目列表", exact: true }).getByRole("button", { name: /专题调研/ }).click();
  await switchProject.click();
  const recent = page.getByRole("navigation", { name: "最近项目", exact: true });
  assert.deepEqual(await recent.getByRole("button").allTextContents(), ["专题调研", "季度汇报"]);
  await recent.getByRole("button", { name: "季度汇报", exact: true }).click();
  await page.reload();
  await page.getByRole("region", { name: "继续上次项目" }).getByRole("button", { name: "继续项目" }).click();
  await page.getByRole("button", { name: "取消收藏当前项目", exact: true }).waitFor();
  await switchProject.click();
  await page.getByRole("navigation", { name: "收藏项目", exact: true }).getByRole("button", { name: "季度汇报", exact: true }).click();
  await page.getByRole("button", { name: "取消收藏当前项目", exact: true }).click();
  await switchProject.click();
  assert.equal(await page.getByRole("navigation", { name: "收藏项目", exact: true }).count(), 0);
  await search.press("Escape");

  await hub.getByRole("tab", { name: "资料", exact: true }).click();
  await hub.getByRole("button", { name: /^调研报告.docx/ }).click();
  const detail = hub.getByRole("region", { name: "资料详情" });
  await detail.getByRole("button", { name: "记录相关进展" }).click();
  const input = () => page.getByRole("textbox", { name: "项目进展内容", exact: true });
  await input().fill("已提交报告初稿，等待评审");
  assert.equal(await hub.getByRole("combobox", { name: "进展关联资料" }).inputValue(), "r1");
  await hub.getByRole("tab", { name: "资料", exact: true }).click();
  await hub.getByRole("button", { name: /^评审意见.pdf/ }).click();
  await detail.getByRole("button", { name: "记录相关进展" }).click();
  assert.equal(await input().inputValue(), "已提交报告初稿，等待评审");
  assert.equal(await hub.getByRole("combobox", { name: "进展关联资料" }).inputValue(), "r1", "a contextual entry must not overwrite an existing draft source");
  await hub.getByRole("combobox", { name: "进展状态" }).selectOption("waiting");
  await hub.getByRole("textbox", { name: "进展日期" }).fill("2026-09-30");
  await input().evaluate(el => { el.focus(); el.setSelectionRange(3, 7); });
  await hub.getByRole("button", { name: "专注录入" }).click();
  const focus = page.getByRole("dialog", { name: "专注记录项目进展" });
  await focus.waitFor();
  assert.equal(await focus.getByRole("textbox", { name: "项目进展内容" }).evaluate(el => el === document.activeElement && el.selectionStart === 3 && el.selectionEnd === 7), true);
  assert.equal(await focus.evaluate(el => el.parentElement.parentElement === document.body), true, "focus dialog stays outside the layout containment");
  await page.evaluate(() => { window.__fixture.failEntry = true; });
  await focus.getByRole("button", { name: "保存本次进展" }).click();
  await focus.getByRole("alert").getByText(/工作记录写入失败/).waitFor();
  assert.equal(await input().inputValue(), "已提交报告初稿，等待评审");
  await page.setViewportSize({ width: 400, height: 700 });
  assert.equal(await focus.evaluate(el => el.scrollWidth <= el.clientWidth + 1), true);
  await mkdir(new URL("../.tmp/ui-verification/", import.meta.url), { recursive: true });
  await page.screenshot({ path: ".tmp/ui-verification/project-focus-narrow.png", fullPage: true, animations: "disabled" });
  await input().press("Escape");
  await focus.waitFor({ state: "detached" });
  assert.equal(await input().inputValue(), "已提交报告初稿，等待评审");
  assert.equal(await input().evaluate(el => el === document.activeElement), true);
  assert.equal(await hub.getByRole("textbox", { name: "进展日期" }).inputValue(), "2026-09-30");
  await page.evaluate(() => { window.__fixture.failEntry = false; });
  await input().press("Control+Enter");
  await hub.getByText("进展已保存，将按实际发生日期进入周报材料", { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => window.__fixture.work.entries[0].occurredOn), "2026-09-30");
  assert.equal(await hub.getByRole("textbox", { name: "进展日期" }).inputValue(), "2026-10-02");
  assert.equal(await hub.getByRole("combobox", { name: "进展状态" }).inputValue(), "in_progress");
  await page.clock.setSystemTime(new Date("2026-10-03T01:00:00+08:00"));
  await input().fill("跨日继续修改报告");
  assert.equal(await hub.getByRole("textbox", { name: "进展日期" }).inputValue(), "2026-10-03", "blank editors start a new record with today's date");
  await input().press("Control+Enter");
  await page.waitForFunction(() => window.__fixture.work.entries.length === 2);
  await hub.getByRole("textbox", { name: "进展日期" }).fill("2026-09-29");
  await input().fill("补记上周提交的材料");
  assert.equal(await hub.getByRole("textbox", { name: "进展日期" }).inputValue(), "2026-09-29", "explicitly chosen historical dates are respected");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await hub.getByRole("button", { name: "专注录入" }).click();
  await page.screenshot({ path: ".tmp/ui-verification/project-focus.png", fullPage: true, animations: "disabled" });
  assert.deepEqual(errors, []);
  console.log("PASS: favorites/recent/search/reload, picker keyboard focus, contextual progress draft protection, focus caret/failure/exit/narrow layout, new-record defaults and midnight/manual dates.");
} finally { await browser.close(); }
