import { chromium } from "playwright";
import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { installFixture } from "./workbench-fixture.mjs";
const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, locale: "zh-CN", timezoneId: "Asia/Shanghai" });
const errors=[];page.on("pageerror",e=>errors.push(e.message));
await page.addInitScript(installFixture);
try {
  await page.goto(process.env.TEST_URL || "http://127.0.0.1:1422");
  await page.getByRole("button",{name:"全部记录",exact:true}).click();
  for (const name of ["专题调研","成果汇报"]) {
    await page.getByRole("textbox",{name:"新项目名称"}).fill(name);
    await page.getByRole("button",{name:"创建项目",exact:true}).click();
    await page.waitForFunction(name=>window.__fixture.work.projects.some(p=>p.name===name),name);
  }
  const select=page.getByRole("combobox",{name:"筛选项目"});
  await select.selectOption({label:"专题调研"});
  const hub=page.getByRole("region",{name:"项目详情"});
  await hub.getByRole("textbox",{name:"项目目标"}).fill("形成调研报告与汇报材料");
  await hub.getByRole("textbox",{name:"项目阶段"}).fill("初稿评审");
  await hub.getByRole("button",{name:"保存目标与阶段"}).click();
  await hub.getByText("项目目标已保存",{exact:true}).waitFor();
  await hub.getByText("添加活动",{exact:true}).click();
  await hub.getByRole("textbox",{name:"活动名称"}).fill("成果评审");
  await hub.getByRole("combobox",{name:"活动类型"}).selectOption("review");
  await page.evaluate(()=>{window.__fixture.failActivity=true;});
  await hub.getByRole("button",{name:"保存活动",exact:true}).click();
  await hub.getByRole("alert").getByText(/活动保存失败/).waitFor();
  assert.equal(await hub.getByRole("textbox",{name:"活动名称"}).inputValue(),"成果评审");
  await page.evaluate(()=>{window.__fixture.failActivity=false;window.__fixture.pickedFiles=["D:\\work\\报告初稿.docx"];});
  await hub.getByRole("button",{name:"保存活动",exact:true}).click();
  await hub.getByText("活动已保存，可以添加本次资料和进展",{exact:true}).waitFor();
  await hub.getByRole("combobox",{name:"资料用途"}).selectOption("output");
  await hub.getByRole("button",{name:"选择本地文件",exact:true}).click();
  await hub.locator(".hub-resources strong").getByText("报告初稿.docx",{exact:true}).waitFor();
  await hub.getByRole("textbox",{name:"搜索项目资料"}).fill("没有这个文件");
  await hub.getByText("未找到匹配文件，可调整关键词；文件正文尚未索引。",{exact:true}).waitFor();
  await hub.getByRole("textbox",{name:"搜索项目资料"}).fill("报告");
  assert.equal(await hub.locator(".hub-resources li").count(),1);
  await hub.getByRole("textbox",{name:"搜索项目资料"}).fill("");
  await hub.getByRole("textbox",{name:"项目进展内容"}).fill("已提交调研初稿，等待评审反馈");
  await hub.getByRole("combobox",{name:"进展状态"}).selectOption("waiting");
  await hub.getByRole("combobox",{name:"进展关联资料"}).selectOption({label:"报告初稿.docx"});
  await page.evaluate(()=>{window.__fixture.failEntry=true;});
  await hub.getByRole("button",{name:"保存本次进展"}).click();
  await hub.getByRole("alert").getByText(/工作记录写入失败/).waitFor();
  assert.equal(await hub.getByRole("textbox",{name:"项目进展内容"}).inputValue(),"已提交调研初稿，等待评审反馈");
  await page.evaluate(()=>{window.__fixture.failEntry=false;});
  await hub.getByRole("button",{name:"保存本次进展"}).click();
  await hub.getByText("进展已保存，将按实际发生日期进入周报材料",{exact:true}).waitFor();
  const entry=await page.evaluate(()=>window.__fixture.work.entries[0]);
  assert.equal(entry.status,"waiting");assert.ok(entry.activityId);assert.ok(entry.resourceId);
  await page.getByRole("button",{name:"修改历史",exact:true}).click();
  const history=page.getByRole("dialog",{name:"工作记录修改历史"});
  await history.getByText(entry.content,{exact:true}).waitFor();
  await history.getByRole("button",{name:"关闭",exact:true}).click();
  await hub.getByRole("textbox",{name:"项目进展内容"}).fill("明天继续核对数据");
  await select.selectOption({label:"成果汇报"});
  await hub.getByText("添加活动",{exact:true}).click();
  await hub.getByRole("combobox",{name:"复用现有活动"}).selectOption({label:"成果评审"});
  await hub.getByRole("button",{name:"关联现有活动"}).click();
  await hub.locator(".hub-resources strong").getByText("报告初稿.docx",{exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>window.__fixture.hub.resources.length),1);
  assert.equal(await page.evaluate(()=>window.__fixture.hub.activities.length),1);
  await select.selectOption({label:"专题调研"});
  assert.equal(await hub.getByRole("textbox",{name:"项目进展内容"}).inputValue(),"明天继续核对数据");
  assert.equal(await hub.getByRole("combobox",{name:"当前活动"}).inputValue(),entry.activityId);
  assert.equal(await hub.getByRole("combobox",{name:"进展关联资料"}).inputValue(),entry.resourceId);
  await page.evaluate(()=>{window.__fixture.missingFile=true;});
  await hub.getByRole("button",{name:"打开",exact:true}).click();
  await hub.getByRole("alert").getByText(/文件不存在/).waitFor();
  await page.evaluate(()=>{window.__fixture.missingFile=false;window.__fixture.pickedFiles="D:\\moved\\报告初稿.docx";});
  await hub.getByRole("button",{name:"重新定位",exact:true}).click();
  await hub.getByText("文件位置已更新，原有关联和进展历史保留",{exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>window.__fixture.hub.resources[0].id),entry.resourceId);
  await mkdir(new URL("../.tmp/ui-verification/",import.meta.url),{recursive:true});
  await page.screenshot({path:".tmp/ui-verification/project-hub.png",fullPage:true});
  await page.setViewportSize({width:400,height:900});
  assert.equal(await hub.evaluate(el=>el.scrollWidth<=el.clientWidth+1),true);
  await page.screenshot({path:".tmp/ui-verification/project-hub-narrow.png",fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole("button",{name:"工作台",exact:true}).click();
  await page.getByRole("button",{name:/每周回顾/}).click();
  const report=page.getByRole("dialog",{name:"生成周报"});
  await report.getByText(/待汇总材料 ·/).click();
  const checks=report.getByRole("checkbox");
  const count=await checks.count();assert.ok(count>1);
  for(let i=1;i<count;i++) await checks.nth(i).uncheck();
  await report.getByRole("button",{name:"整理草稿",exact:true}).click();
  await report.getByRole("textbox",{name:"周报正文"}).waitFor();
  assert.equal(await page.evaluate(()=>window.__fixture.reports[0].sources.length),1);
  assert.deepEqual(errors,[]);
  console.log("PASS: project goal, activity retry, shared files/activities, linked progress, retained draft, history, missing file relocation, report selection and narrow layout.");
} finally {await browser.close();}
