import { chromium } from "playwright";
import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { installFixture } from "./workbench-fixture.mjs";
const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || "chrome", headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, locale: "zh-CN", timezoneId: "Asia/Shanghai" });
const page = await context.newPage(); const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.addInitScript(installFixture);
try {
  await page.goto(process.env.TEST_URL || "http://127.0.0.1:1422");
  await page.getByRole("heading", { name: "工作台", exact: true }).waitFor();
  await page.getByRole("textbox", { name: "工作内容", exact: true }).fill("客户报价已提交，等待确认");
  await page.getByRole("button", { name: "全部记录", exact: true }).click();
  assert.equal(await page.getByRole("textbox", { name: "工作内容" }).inputValue(), "客户报价已提交，等待确认");
  await page.getByRole("textbox", { name: "新项目名称" }).fill("客户交付");
  await page.getByRole("button", { name: "创建项目", exact: true }).click();
  await page.getByRole("combobox", { name: "所属项目", exact: true }).selectOption({ label: "客户交付" });
  await page.getByRole("combobox", { name: "工作状态", exact: true }).selectOption("waiting");
  await page.evaluate(() => { window.__fixture.failEntry = true; });
  await page.getByRole("button", { name: "保存记录", exact: true }).click();
  await page.getByRole("alert").getByText(/工作记录写入失败/).waitFor();
  assert.equal(await page.getByRole("textbox", { name: "工作内容" }).inputValue(), "客户报价已提交，等待确认");
  await page.evaluate(() => { window.__fixture.failEntry = false; });
  await page.getByRole("button", { name: "保存记录", exact: true }).click();
  await page.locator(".work-entry").getByText("客户报价已提交，等待确认", { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => window.__fixture.work.entries.length), 1);
  await page.getByText("关联会议与待办 · 按项目整理周报材料").click();
  await page.getByRole("combobox", { name: "会议项目：产品体验优化 · 周例会", exact: true }).selectOption({ label: "客户交付" });
  await page.waitForFunction(() => window.__fixture.work.links["meeting:m1"]);
  await mkdir(new URL("../.tmp/ui-verification/", import.meta.url), { recursive: true });
  await page.screenshot({ path: ".tmp/ui-verification/work-journal.png", fullPage: true });
  await page.getByRole("button", { name: "工作台", exact: true }).click();
  await page.getByRole("button", { name: /每周回顾/ }).click();
  const dialog = page.getByRole("dialog", { name: "生成周报" });
  await dialog.getByRole("combobox", { name: "周报项目" }).selectOption({ label: "客户交付" });
  await dialog.getByRole("button", { name: "整理草稿", exact: true }).click();
  await dialog.getByRole("textbox", { name: "周报正文" }).waitFor();
  assert.match(await dialog.getByRole("textbox", { name: "周报正文" }).inputValue(), /客户报价已提交/);
  assert.equal(await page.evaluate(() => window.__fixture.reports[0].sources.length), 2);
  await dialog.getByRole("textbox", { name: "周报正文" }).fill("# 已核对的周报\n\n报价待客户确认。");
  await dialog.getByRole("button", { name: "关闭", exact: true }).click();
  await dialog.getByRole("alert").getByText(/未保存/).waitFor();
  await page.evaluate(() => { window.__fixture.failReport = true; });
  await dialog.getByRole("button", { name: "保存修改", exact: true }).click();
  await dialog.getByRole("alert").getByText(/周报保存失败/).waitFor();
  assert.match(await dialog.getByRole("textbox", { name: "周报正文" }).inputValue(), /已核对/);
  await page.evaluate(() => { window.__fixture.failReport = false; });
  await dialog.getByRole("button", { name: "保存修改", exact: true }).click();
  await dialog.getByText("修改已保存", { exact: true }).waitFor();
  await page.evaluate(() => { window.__fixture.failReport = true; });
  await dialog.getByRole("button", { name: "AI 生成周报", exact: true }).click();
  await dialog.getByRole("alert").getByText(/生成失败/).waitFor();
  assert.match(await dialog.getByRole("textbox", { name: "周报正文" }).inputValue(), /已核对/);
  await page.evaluate(() => { window.__fixture.failReport = false; });
  await dialog.getByRole("button", { name: "关闭", exact: true }).click();
  await page.getByRole("button", { name: /每周回顾/ }).click();
  const reportId = await page.evaluate(() => window.__fixture.reports[0].id);
  await dialog.getByRole("combobox", { name: "周报档案" }).selectOption(reportId);
  assert.match(await dialog.getByRole("textbox", { name: "周报正文" }).inputValue(), /已核对/);
  await page.screenshot({ path: ".tmp/ui-verification/weekly-report.png", fullPage: true });
  await page.setViewportSize({ width: 400, height: 800 });
  assert.equal(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth + 1), true);
  await page.screenshot({ path: ".tmp/ui-verification/weekly-report-narrow.png", fullPage: true });
  await dialog.getByRole("button", { name: "关闭", exact: true }).click();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole("button", { name: "设置", exact: true }).click();
  await page.getByRole("button", { name: /本地 API \/ MCP/ }).click();
  await page.getByRole("button", { name: "开启本地接入", exact: true }).click();
  await page.getByRole("button", { name: "复制 MCP 配置", exact: true }).waitFor();
  await page.screenshot({ path: ".tmp/ui-verification/local-access.png", fullPage: true });
  await page.getByRole("button", { name: "停止接入", exact: true }).click();
  await page.getByRole("button", { name: "开启本地接入", exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log("PASS: capture draft navigation, project assignment, save failure/retry, report sources/filter, archive reopen, generation failure preserves edits, dirty close guard, narrow report, local access controls.");
} finally { await browser.close(); }
